document.write("<h2>");
document.write("Más información sobre el navegaodr");
document.write("</h2>");
document.write("<p>");
document.write("Versión: ");
document.write(navegador.version);
document.write("</p>");
document.write("<p>");
document.write("Vendedor: ");
document.write(navegador.vendedor);
document.write("</p>");
document.write("<p>");
document.write("Agente de usuario: ");
document.write(navegador.agente);
document.write("</p>");
document.write("<p>");
document.write("Java activo: ");
document.write(navegador.javaEnabled);
document.write("</p>");
document.write("<p>");
document.write("Plataforma: ");
document.write(navegador.plataforma);
document.write("</p>");
document.write("<p>");
document.write("Online: ");
document.write(navegador.isOnline);
document.write("</p>");